---
- name: VM create on OCP Virt
  hosts: localhost

  tasks:
  - name: VM create with Kubevirt module
    community.kubevirt.kubevirt_vm:
      state: running
      name: 05-zpa-cockpit
      namespace: vm-demo
      validate_certs: no
#      username: admin
#      password: Start123