
---
- name: VM create on OCP Virt
  hosts: localhost
  gather_facts: no

  tasks:
  - name: VM create with Kubevirt module
    community.kubevirt.kubevirt_vm:
      name: jskrhel8
      state: running
      namespace: vm-demo
      template: myvmtemplate
      template_parameters:
        volumes: rootdisk
        networks: bridge
        interfaces: default
        disks: rootdisk
      validate_certs: no
      host: https://api.zpa.redhat.lab:6443
      username: zibi
      api_key: sha256~AoKr5mV48go0PpoQF9PtrFuSwF6mMoielCJfABTENZY