---
- name: Stop VM
  hosts: localhost
  gather_facts: no

  vars_file: files/ocp_virt_creds.yml

  tasks:
  - name: Stop VM with Kubevirt module
    community.kubevirt.kubevirt_vm:
      name: "{{ ocp_vm_name_to_stop }}"
      state: stopped
      namespace: vm-demo
      validate_certs: no
      host: "{{ ocp_host_url }}"
      username: "{{ ocp_username }}"
      api_key: "{{ ocp_api_key }}"